#!/bin/bash

# Loads nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

isNodeJsNotInstalled=$(command -v nodejs)

if [[ -z $isNodeJsNotInstalled ]]; then
	nvm install node
else
	nvm install node --reinstall-packages-from=node
fi
