#!/bin/bash

# list of files and directories to link them
files[0]="scripts"
files[1]=".bash_atyroid"
files[2]=".bash_aliases"

# Import helper functions
source $SCRIPTS_HOME/functions.sh

# link needed files and directories in home path
path="source/Development-Environment"
links $files $path
